name: Feature Request
description: File a feature request
title: "[FEATURE]: "
labels: ["feature"]
projects: ["the-bwc/5"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: what-feature
    attributes:
      label: What feature would you like to see?
      description: Please describe the feature you would like to see.
      placeholder: Tell us what you want!
      value: "A feature request!"
    validations:
      required: true
  - type: textarea
    id: why-feature
    attributes:
      label: Why do you want this feature?
      description: Please describe why you want this feature.
      placeholder: Tell us why you want it!
      value: "I want this feature because..."
    validations:
      required: true