name: "Feature Request"
description: Create a new ticket for a feature request.
title: "[FEATURE] - <title>"
labels: ["feature"]
projects: ["the-bwc/5"]
body:
  - type: textarea
    id: what-feature
    attributes:
      label: "What feature would you like to see?"
      description: Please describe the feature you would like to see.
      placeholder: Tell us what you want!
    validations:
      required: true
  - type: textarea
    id: why-feature
    attributes:
      label: "Why do you want this feature?"
      description: Please describe why you want this feature.
      placeholder: Tell us why you want it!
    validations:
      required: false
