name: Changelog
on:
  issues:
    types:
      - closed

permissions:
  contents: write

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker://patrickpedersen/autochangelog@latest
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        changelog_file: CHANGELOG.md